name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      HASH: $(git rev-parse --short "$GITHUB_SHA")
      BRANCH: ${GITHUB_REF##*/}
      SERVICE_NAME: combo-generator
      PROJECT_ID: combo-generator
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_SERVICE_ACCOUNT_KEY }}
          project_id: combo-generator
          export_default_credentials: true
      - name: Image
        run: |-
          docker build -t eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA .
      - run: |
          gcloud auth configure-docker -q
      - name: Build
        run: |-
          docker push eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA          
      
