name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-image:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    env:
      HASH: $(git rev-parse --short "$GITHUB_SHA")
      BRANCH: ${GITHUB_REF##*/}
      SERVICE_NAME: combo-generator
      PROJECT_ID: combo-generator
    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/586673076523/locations/global/workloadIdentityPools/github-auth-pool/providers/github-oidc-provider'
          service_account: 'github-actions@combo-generator.iam.gserviceaccount.com'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: Image
        run: |-
          docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$HASH .
      - run: |
          gcloud auth configure-docker -q
      - name: Build
        run: |-
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$HASH
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: 'combo-generator'
          region: 'europe-west3'
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ env.HASH }}

